### ISSUE TITLE
Add a LICENSE file (and refer to it in the README)

### ISSUE THREAD

**Issue by zostay** [Raku/vim-raku#6]
Migration of https://github.com/vim-perl/vim-perl6/issues/18 by @Tyil 

# Description of issue

This project currently does not carry a LICENSE. In the spirit of free software I'd like it to adopt a free license clearly in the project root. If possible, refer to the license in the README.md as well.

Since this is something we should decide with all contributors, all of them have been tagged in this issue. Please respond to this issue with the license you are OK with to put on this codebase.

**Comment by Tyil** [comment]
On Thu, 02 Jan 2020 14:08:30 -0800
Sterling Hanenkamp <notifications@github.com> wrote:

> Migration of https://github.com/vim-perl/vim-perl6/issues/18 by @Tyil 
> 
> # Description of issue
> 
> This project currently does not carry a LICENSE. In the spirit of
> free software I'd like it to adopt a free license clearly in the
> project root. If possible, refer to the license in the README.md as
> well.
> 
> Since this is something we should decide with all contributors, all
> of them have been tagged in this issue. Please respond to this issue
> with the license you are OK with to put on this codebase.
> 

I'm OK with any license that is approved by the FSF[1], with a
preference towards (A)GPLv3.

[1]: https://www.gnu.org/licenses/license-list.html#SoftwareLicenses

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

social: https://soc.fglt.nl/tyil
git:    https://gitlab.com/tyil/

**Comment by zostay** [comment]
I am adding my votes in which are: MIT, (any)

This should be done. I'm going to use a very simple ranked choice voting system to tally votes. As there were up to 4 choices made, I give the first choice of anyone 4 votes, the second choice gets 3 votes, the third 2 votes, and the final just 1 vote. My tallys are as follows:

1. (Any) 19 votes, 31%
2. MIT 17 votes, 28%
3. vim 10 votes, 16%
4. GPL/GPL 3 8 votes, 13%
5. ISC 4 votes, 7%
6. AGPL 4 votes, 7%
7. BSD 3 votes, 5%

I am reading "(any)" as meaning that any FSF or OSI approved license would be considered reasonable. Therefore, "(any)" and "MIT" make up a plurality, which indicates to me that no runoff is necessary as they hold a plurality together.

Therefore, I will go ahead and add the MIT license to plugin as well as add appropriate documentation elsewhere to that effect. The license need not be set in stone, so if someone disagrees with my logic or the way I counted votes, please comment and we can discuss it.
